#include "ConvexHull.h"

#include <assert.h>

namespace Engine
{
namespace Math
{
ConvexHull::ConvexHull() = default;
ConvexHull::~ConvexHull() = default;

// GetConvexHull:
// Returns the convex hull generated by QuickHull
const std::vector<Vector3>& ConvexHull::getVertexBuffer() const
{
    return vertices;
}
const std::vector<UINT>& ConvexHull::getIndexBuffer() const
{
    return indices;
}

// TransformPoints:
// Applies the transform to the points
void ConvexHull::transformPoints(const Transform* transform)
{
    const Matrix4 m_transform = transform->transformMatrix();

    for (int i = 0; i < vertices.size(); i++)
    {
        Vector3 transformed = (m_transform * Vector4(vertices[i], 1)).xyz();
        vertices[i] = transformed;
    }
}

} // namespace Math
} // namespace Engine